FROM gradle:jdk15
EXPOSE 8080:8080
#RUN mkdir /app
COPY src ./src
COPY build.gradle.kts ./build.gradle.kts
RUN gradle installDist
#COPY ./build/install/nica-emd/ /app/
#COPY ./build/processedResources/jvm/main/ /app/resources/main
#WORKDIR /app/bin
WORKDIR ./build/install/nica-emd/
CMD ["./nica-emd"]

