FROM gradle:7.6.4-jdk17 AS builder
COPY src ./src
COPY build.gradle.kts ./build.gradle.kts
COPY settings.gradle.kts ./settings.gradle.kts
COPY gradle.properties ./gradle.properties
RUN gradle installDist

FROM azul/zulu-openjdk:17
EXPOSE 8080:8080
COPY --from=builder /home/gradle/build/install/nica-ems/ /app/
COPY --from=builder /home/gradle/build/processedResources/jvm/main/ /app/resources/main
WORKDIR /app/bin
CMD ["./nica-ems"]
