event_db:
  host: bmn-eventdb.jinr.ru
  port: 5000
  db_name: event_db
  user: postgres
  password: example

condition_db:
  host: bmn-unidb.jinr.ru
  port: 5432
  db_name: uni_db
  user: db_reader
  password: reader_pass
